[package]
name = "redis-promql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = { version = "0.8.6", features = ["serde"] }
binary-merge = "0.1.2"
bincode = { version = "2.0.0-rc.3", features = ["alloc", "serde"] }
chrono = { version = "0.4.31", features = ["serde"] }
dynamic-lru-cache = "0.2.1"
get-size = {  version =  "0.1", features = ["derive"] }
lazy_static = { version = "1.4.0", features = [] }
linkme = "0.3.17"
lru_time_cache = "0.11.11"
metricsql_common = { git = "https://github.com/ccollie/metricsql", branch = "main" }
metricsql_encoding = { git = "https://github.com/ccollie/metricsql", branch = "main" }
metricsql_engine = { git = "https://github.com/ccollie/metricsql", branch = "main" }
metricsql_parser = { git = "https://github.com/ccollie/metricsql", branch = "main" }
q_compress = "0.11.7"
redis-module = "2.0.7"
redis-module-macros = "2.0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = { version = "0.9.27", features = [] }
thiserror = "1"
rayon = "1.8.0"
regex = "1.10.2"
regex-syntax = { version = "0.8.2", features = [] }
roaring = { version = "0.10.2", features = ["serde"]}
xxhash-rust = { version = "0.8.7", features = ["xxh3"] }
rand = "0.8.5"
rand_distr = "0.4.3"

[lib]
crate-type=["rlib", "cdylib"]