[package]
name = "redis-promql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = { version = "0.8.3", features = [] }
chrono = { version = "0.4.31", features = ["serde"] }
bincode = { version = "2.0.0-rc.3", features = ["alloc", "serde"] }
lazy_static = { version = "1.4.0", features = [] }
linkme = "0.3.16"
lru_time_cache = "0.11.11"
metricsql_engine = { git = "https://github.com/ccollie/metricsql", branch = "main" }
metricsql_parser = { git = "https://github.com/ccollie/metricsql", branch = "main" }
redis-module = "2.0.5"
redis-module-macros = "2.0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = { version = "0.9.25", features = [] }
thiserror = "1"
rayon = "1.8.0"
regex = "1.10.0"
regex-syntax = { version = "0.8.0", features = [] }
roaring = { version = "0.10.2", features = ["serde"]}
xxhash-rust = { version = "0.8.7", features = ["xxh3"] }
dynamic-lru-cache = "0.2.1"

[lib]
crate-type=["rlib", "cdylib"]