pub const NO_SERIES_FOUND: &str = "ERR no series found";
pub const SERIES_NOT_FOUND: &str = "ERR series not found";
pub const CAPACITY_FULL: &str = "ERR capacity full";
pub const INTERNAL_ERROR: &str = "ERR internal error";
pub const INVALID_CONFIGURATION: &str = "ERR invalid configuration";
pub const SERIALIZATION_FAIL: &str = "ERR serialization failure";
pub const DESERIALIZE_ERROR: &str = "ERR cannot deserialize";
pub const DUPLICATE_SAMPLE: &str = "ERR duplicate sample";
pub const INVALID_METRICS: &str = "ERR invalid metric";
pub const INVALID_CHUNK_COMPRESSION_METHOD: &str = "ERR invalid chunk compression method";
pub const INVALID_DUPLICATE_POLICY: &str = "ERR invalid duplicate policy";
pub const INVALID_TIMESTAMP: &str = "ERR invalid timestamp";
pub const INVALID_DURATION: &str = "ERR invalid duration";
pub const INVALID_NUMBER: &str = "ERR invalid number";
pub const INVALID_SERIES_SELECTOR: &str = "ERR invalid url";
pub const SAMPLE_TOO_OLD: &str = "ERR sample timestamp exceeds retention period";
pub const CANNOT_ADD_SAMPLE: &str = "ERR could not add sample";

pub const ERROR_FETCHING_SAMPLE: &str = "ERR fetching sample";